apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluentbit
  namespace: tanzu-packages
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: fluentbit-overlay-secret
spec:
  serviceAccountName: tanzu-package-fluentbit-sa
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.5+vmware.2-tkg.1
  values:
  - secretRef:
      name: fluentbit-packages-values