# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-package-prometheus-role
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  - certificates
  verbs:
  - get
  - list
  - use
  - create
  - update
- apiGroups:
  - "projectcontour.io"
  resources:
  - httpproxies
  verbs:
  - get
  - create
  - update
  - delete
  - use
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - use
  - create
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclass
  verbs:
  - "list"
  - "use"
  - "get"
- apiGroups:
    - ""
  resources:
  - events
  - nodes
  - nodes/stats
  - nodes/metrics
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  - ingresses
  - replicasets
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - "" 
  resources:
  - endpoints
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - "" 
  resources:
  - ingresses
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - "" 
  resources:
  - limitranges
  verbs:
  - watch
  - list
- apiGroups:
  - "" 
  resources:
  - replicationcontrollers
  verbs:
  - watch
  - list
- apiGroups:
  - "" 
  resources:
  - resourcequotas
  verbs:
  - watch
  - list
- apiGroups:
  - "admissionregistration.k8s.io" 
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - watch
  - list
- apiGroups:
  - "apps" 
  resources:
  - replicasets
  - statefulsets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - "autoscaling" 
  resources:
  - horizontalpodautoscalers
  verbs:
  - watch
  - list
- apiGroups:
  - "batch" 
  resources:
  - cronjobs
  - jobs
  verbs:
  - watch
  - list
- apiGroups:
  - "certificates.k8s.io" 
  resources:
  - certificatesigningrequests
  verbs:
  - watch
  - list
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
- apiGroups:
  - "networking.k8s.io" 
  resources:
  - networkpolicies
  - ingresses
  - ingresses/status
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - "policy" 
  resources:
  - poddisruptionbudgets
  verbs:
  - watch
  - list
- apiGroups:
  - "storage.k8s.io" 
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - use
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - use
  - create
  - update
  - list
  - delete
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  # resourceNames:
  # - vmware-system-restricted
  # - prometheus-node-exporter
  verbs:
  - use
  - get
  - update
- apiGroups:
    - ""
  resources:
    - podsecuritypolicies
  resourceNames:
    - "node-exporter"
  verbs:
    - use