apiVersion: v1
kind: Secret
metadata:
  name: prometheus-overlay-secret
  namespace: tanzu-packages
stringData:
  alertmanager-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.and_op(overlay.subset({"kind": "Deployment"}), overlay.subset({"metadata": {"name": "alertmanager"}}))
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by="name",expects="0+"
            - name: alertmanager
              args:
                - --cluster.listen-address=

    #@overlay/match by=overlay.subset({"kind":"ClusterRole", "metadata":{"name":"prometheus-node-exporter"}})
    ---
    rules:
    - apiGroups: ['policy']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
      - prometheus-node-exporter