ingress:
  enabled: true
  virtual_host_fqdn: "prometheus2.lab.uhtec.com"
  prometheus_prefix: "/"
  alertmanager_prefix: "/alertmanager/"
  prometheusServicePort: 80
  alertmanagerServicePort: 80
prometheus:
  pvc:
    storageClassName: tanzu-storage
alertmanager:
  pvc:
    storageClassName: tanzu-storage