apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: grafana
  namespace: tanzu-packages
spec:
  serviceAccountName: tanzu-package-grafana-sa
  packageRef:
    refName: grafana.tanzu.vmware.com
    versionSelection:
      constraints: 7.5.7+vmware.2-tkg.1
  values:
  - secretRef:
      name: grafana-packages-values